v4l2_capture:
  allocator: ~
  device: "/dev/video0"
  width: 1280
  height: 720
  fps: 10
  numBuffers: 4
  pixel_format: "YUYV"
holoviz:
  window_title: "Camera Stream"
  width: 854
  height: 480
  tensors: [ ]
  
holoviz_90:
  window_title: "Camera Stream"
  width: 854
  height: 480
  tensors: [ ]

rotate90:
  quarters: 0
